# Generated by Django 2.1.2 on 2018-10-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangoboard',
            name='hits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
