# Generated by Django 2.1.2 on 2018-10-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoBoard',
            fields=[
                ('hakbun', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('irum', models.CharField(blank=True, max_length=10)),
                ('kor', models.IntegerField(blank=True, null=True)),
                ('eng', models.IntegerField(blank=True, null=True)),
                ('math', models.IntegerField(blank=True, null=True)),
                ('tot', models.IntegerField(blank=True, null=True)),
                ('avg', models.FloatField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
    ]
