# Generated by Django 2.1.2 on 2018-10-18 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sungjuk', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DjangoBoard',
            new_name='DjangoSungjuk',
        ),
    ]
